### ISSUE TITLE
Geht nicht

### ISSUE THREAD

**Issue by ItzN00bPvP** [EnderKill98/ProxChat#1]
![image](https://github.com/EnderKill98/ProxChat/assets/26351148/ce14cd3c-4b6a-4d4a-91bc-0c58c58dbc4d)

**Comment by EnderKill98** [comment]
See branches:

 - [0.1.0-mc1.20.1](https://github.com/EnderKill98/ProxChat/tree/patch/0.1.0-mc1.20.1): https://transfer.cosmos-ink.net/m4PKfvrn0q/proxchat-0.1.0-mc1.20.1.jar
 - [0.1.0-mc1.20.2](https://github.com/EnderKill98/ProxChat/tree/patch/0.1.0-mc1.20.2): https://transfer.cosmos-ink.net/E0cYLFRTKG/proxchat-0.1.0-mc1.20.2.jar
